platform: linux/arm

pipeline:
  docker-build:
    image: plugins/docker:linux-arm
    repo: justinbarrick/drone-helm
    pull_image: false
    tags: 
      - arm
      - k1.8.1-h2.7.0
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      branch: [master]

  manifest:
    image: docker:18.02.0-ce
    commands:
      - env
      - docker login
      - mkdir configs
      - echo '{"experimental":"enabled"}' > configs/config.json
      - docker --config configs manifest create justinbarrick/drone-helm:latest quay.io/ipedrazas/drone-helm:latest justinbarrick/drone-helm:arm
      - docker --config configs manifest annotate justinbarrick/drone-helm:latest justinbarrick/drone-helm:arm --arch arm
      - docker --config configs manifest annotate justinbarrick/drone-helm:latest quay.io/ipedrazas/drone-helm:latest --arch amd64
      - docker --config configs manifest push justinbarrick/drone-helm:latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      branch: [master]

  slack:
    image: plugins/slack:linux-arm
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    when:
      status: [success, failure]

plugin:
  name: drone-helm-arm
  desc: Execute helm to
  type: deploy
  image: justinbarrick/drone-helm
  labels:
    - deploy
    - kubernetes
    - helm
